### ISSUE TITLE
Multiple devices - same IP different port

### ISSUE THREAD

**Issue by pfunkylol** [netfishers-onl/Netshot#215]
Hello,

I am encountering a strange situation ( haven't added any other devices, so I can't say it worked before ) where multiple devices have the same public IP but different ports forwarded/NATed for SSH.
e.g.
device 1 : 1.1.1.1 port 122 > 10.0.0.252:22
device 2 : 1.11.1 port 222 > 10.0.0.253:22

I can add the first device using in the field IP address 10.0.0.252 and enabling Override connection settings entering 1.1.1.1 and ssh port 122
The problem is when I add the 2nd device with 10.0.0.253 and 1.1.1.1 and ssh 222 , I get Error: Database error .

In the logs on the server I see 
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '-728605695' for key 'device.UK_49k44bri62v926c9f4uw4t68q' 
where -728605695 is the ipv4_address value in the database table _device_ for the first device entered.

Any ideas on how to solve it ?

**Comment by SCadilhac** [comment]
You must provide a unique Management IP (_IP Address_ field) for each device, even if you configure the same connection IP (_Connect to this IP_ field) for multiple ones.

**Comment by pfunkylol** [comment]
Hi.
 I did exactly that, didn't worked.

**Comment by SCadilhac** [comment]
Sorry for misreading.
Should be fixed by https://github.com/netfishers-onl/Netshot/commit/7cd4bcc2c07e02cd98ffd85946fc808fccfe6ad5
=> new release, to be published soon, should include the fix

**Comment by pfunkylol** [comment]
Thank you.

**Comment by pfunkylol** [comment]
Hi @SCadilhac , with the new release the error still persists. Tried to add another device and get the same error message in GUI : 
`Error! Database error` 
and in logs
`Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '-728605695' for key 'device.UK_49k44bri62v926c9f4uw4t68q'
`

**Comment by SCadilhac** [comment]
I will try to have a look, but I strongly recommend to use PostgreSQL - we don't do testing on MySQL anymore.

**Comment by pfunkylol** [comment]
I can confirm that with postgreSQL it works just fine.

**Comment by SCadilhac** [comment]
> I can confirm that with postgreSQL it works just fine.

Great, thank you
